Diagrams for categorical data
=========================

```{r echo=FALSE}
opts_knit$set(self.contained=FALSE)
opts_chunk$set(tidy=FALSE, message=FALSE, warning=FALSE, comment="")
```

Install required packages
-------------------------

[`plotrix`](http://cran.r-project.org/package=plotrix)

```{r}
wants <- c("plotrix")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Barplots
-------------------------

### Simulate data
    
```{r}
set.seed(1.234)
dice  <- sample(1:6, 100, replace=TRUE)
(dTab <- table(dice))
```

###  Simple barplot

```{r}
barplot(dTab, ylim=c(0, 30), xlab="Augenzahl", ylab="N", col="black",
        main="Absolute Haeufigkeiten")
```

```{r eval=FALSE}
barplot(prop.table(dTab), ylim=c(0, 0.3), xlab="Augenzahl",
        ylab="relative Haeufigkeit", col="gray50", main="Relative Haeufigkeiten")
```

### Barplots for contingency tables of two variables
#### Stacked barplot

```{r}
roll1   <- dice[1:50]
roll2   <- dice[51:100]
rollAll <- rbind(table(roll1), table(roll2))
rownames(rollAll) <- c("first", "second"); rollAll

barplot(rollAll, beside=FALSE, legend.text=TRUE, xlab="Augenzahl", ylab="N",
        main="Absolute Haeufigkeiten in zwei Substichproben")
```

#### Grouped barplot

```{r}
barplot(rollAll, beside=TRUE, ylim=c(0, 15), col=c("red", "green"),
        legend.text=TRUE, xlab="Augenzahl", ylab="N",
        main="Absolute Haeufigkeiten in zwei Substichproben")
```

Spineplot
-------------------------

```{r}
N      <- 100
age    <- sample(18:45, N, replace=TRUE)
drinks <- c("beer", "red wine", "white wine")
pref   <- factor(sample(drinks, N, replace=TRUE))
xRange <- round(range(age), -1) + c(-10, 10)
lims   <- c(18, 25, 35, 45)
spineplot(x=age, y=pref, xlab="Altersstufe", ylab="Getraenk", breaks=lims,
          main="Bevorzugte Getraenke pro Altersstufe")
```

Mosaic-plot
-------------------------

```{r}
ageCls <- cut(age, breaks=lims, labels=LETTERS[1:(length(lims)-1)])
group  <- factor(sample(letters[1:2], N, replace=TRUE))
cTab   <- table(ageCls, pref, group)
mosaicplot(cTab, cex.axis=1)
```

Pie-charts
-------------------------

### 2-D pie-chart

```{r}
dice <- sample(1:6, 100, replace=TRUE)
dTab <- table(dice)
pie(dTab, col=c("blue", "red", "yellow", "pink", "green", "orange"),
    main="Relative Haeufigkeiten beim Wuerfeln")

dTabFreq <- prop.table(dTab)
textRad  <- 0.5
angles   <- dTabFreq * 2 * pi
csAngles <- cumsum(angles)
csAngles <- csAngles - angles/2
textX    <- textRad * cos(csAngles)
textY    <- textRad * sin(csAngles)
text(x=textX, y=textY, labels=dTabFreq)
```

### 3-D pie-chart

```{r}
library(plotrix)
pie3D(dTab, theta=pi/4, explode=0.1, labels=names(dTab))
```

Conditional density plot
-------------------------

```{r}
N    <- 100
X    <- rnorm(N, 175, 7)
Y    <- 0.5*X + rnorm(N, 0, 6)
Yfac <- cut(Y, breaks=c(-Inf, median(Y), Inf), labels=c("lo", "hi"))
myDf <- data.frame(X, Yfac)
```

```{r}
cdplot(Yfac ~ X, data=myDf)
```

Useful packages
-------------------------

More plot types for categorical data are available in packages [`vcd`](http://cran.r-project.org/package=vcd) and [`vcdExtra`](http://cran.r-project.org/package=vcdExtra).

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:plotrix))
```
