Visualize univariate and bivariate distributions
=========================

```{r echo=FALSE}
opts_knit$set(self.contained=FALSE)
opts_chunk$set(tidy=FALSE, message=FALSE, warning=FALSE, comment="")
```

TODO
-------------------------

 - link to diagCategorical, diagScatter, diagMultivariate, diagAddElements, diagBounding
 - new R 2.15.1+ `qqplot()` options `distribution` and `probs`

Install required packages
-------------------------

[`car`](http://cran.r-project.org/package=car), [`hexbin`](http://cran.r-project.org/package=hexbin)

```{r}
wants <- c("car", "hexbin")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Histograms
-------------------------

### Histogram with absolute class frequencies
    
```{r}
set.seed(1.234)
x <- rnorm(200, 175, 10)
hist(x, xlab="x", ylab="N", breaks="FD")
```

### Add individual values and theoretical density function

```{r}
hist(x, freq=FALSE, xlab="x", ylab="relative Haeufigkeit",
     breaks="FD", main="Histogramm und Normalverteilung")
rug(jitter(x))
curve(dnorm(x, mean(x), sd(x)), lwd=2, col="blue", add=TRUE)
```

### Add estimated density function

```{r}
hist(x, freq=FALSE, xlab="x", breaks="FD",
     main="Histogram and density estimate")
lines(density(x), lwd=2, col="blue")
rug(jitter(x))
```

To compare histograms from two groups, see `histbackback()` from package [Hmisc](http://cran.r-project.org/package=Hmisc).

Stem and leaf plot
-------------------------

```{r}
y <- rnorm(100, mean=175, sd=7)
stem(y)
```

Boxplot
-------------------------

```{r}
Nj <- 40
P  <- 3
DV <- rnorm(P*Nj, mean=100, sd=15)
IV <- gl(P, Nj, labels=c("Control", "Group A", "Group B"))
```

```{r}
boxplot(DV ~ IV, ylab="Score", col=c("red", "blue", "green"),
        main="Boxplots der Scores in 3 Gruppen", cex.lab=1.2)
stripchart(DV ~ IV, pch=16, col="darkgray", vert=TRUE, add=TRUE)
```

```{r}
xC <- DV[IV == "Control"]
xA <- DV[IV == "Group A"]
boxplot(xC, xA)
```

Dotchart
-------------------------

```{r}
Nj  <- 5
DV1 <- rnorm(Nj, 20, 2)
DV2 <- rnorm(Nj, 25, 2)
DV  <- c(DV1, DV2)
IV  <- gl(2, Nj)
Mj  <- tapply(DV, IV, FUN=mean)
```

```{r}
dotchart(DV, gdata=Mj, pch=16, color=rep(c("red", "blue"), each=Nj),
         gcolor="black", labels=rep(LETTERS[1:Nj], 2), groups=IV, xlab="AV",
         ylab="Gruppen",
         main="Individuelle Ergebnisse und Mittelwerte aus 2 Gruppen")
```

Stripchart
-------------------------

```{r}
Nj   <- 25
P    <- 4
dice <- sample(1:6, P*Nj, replace=TRUE)
IV   <- gl(P, Nj)

```{r}
stripchart(dice ~ IV, xlab="Augenzahl", ylab="Gruppe", pch=1,  col="blue",
           main="Wuerfelwuerfe - 4 Gruppen", sub="jitter-Methode", method="jitter")
stripchart(dice ~ IV, xlab="Augenzahl", ylab="Gruppe", pch=16, col="red",
           main="Wuerfelwuerfe - 4 Gruppen", sub="stack-Methode",  method="stack")
```

QQ-plot
-------------------------

```{r}
DV1 <- rnorm(200)
DV2 <- rf(200, df1=3, df2=15)
qqplot(DV1, DV2, xlab="Quantile N(0, 1)", ylab="Quantile F(3, 15)",
       main="Vergleich der Quantile von N(0, 1) und F(3, 15)-Verteilung")
```

```{r}
height <- rnorm(100, mean=175, sd=7)
qqnorm(height)
qqline(height, col="red", lwd=2)
```

Empirical cumulative distribution function
-------------------------

```{r}
vec <- round(rnorm(10), 1)
Fn  <- ecdf(vec)
plot(Fn, main="Empirische kumulierte Haeufigkeitsverteilung", cex.lab=1.4)
curve(pnorm, add=TRUE, col="gray", lwd=2)
```

Joint distribution of two variables in separate groups
-------------------------

### Simulate data

```{r}
N  <- 200
P  <- 2
x  <- rnorm(N, 100, 15)
y  <- 0.5*x + rnorm(N, 0, 10)
IV <- gl(P, N/P, labels=LETTERS[1:P])
```

### Identify group membership by plot symbol and color

```{r}
plot(x, y, pch=c(4, 16)[unclass(IV)], lwd=2, col=c("black", "blue")[unclass(IV)],
     main="Gemeinsame Verteilung getrennt nach Gruppen")
legend(x="topleft", legend=c("Gruppe A", "Gruppe B"), pch=c(4, 16),
       col=c("black", "blue"))
```

### Add distribution ellipse

```{r}
library(car)
dataEllipse(x, y, xlab="x", ylab="y", asp=1, levels=0.5, lwd=2, center.pch=16,
            col="blue", main="Gemeinsame Verteilung zweier Variablen")
legend(x="bottomright", legend=c("Datenpunkte", "Zentroid", "Streuungsellipse"),
       pch=c(1, 16, NA), lty=c(NA, NA, 1), col=c("black", "blue", "blue"))
```

Joint distribution of two variables with many observations
-------------------------

### Using transparency

```{r}
N  <- 5000
xx <- rnorm(N, 100, 15)
yy <- 0.4*xx + rnorm(N, 0, 10)
plot(xx, yy, pch=16, col=rgb(0, 0, 1, 0.3))
```

### Smooth scatter plot

```{r}
smoothScatter(xx, yy, bandwidth=4)
```

### Hexagonal 2-D binning

```{r}
library(hexbin)
res <- hexbin(xx, yy, xbins=20)
plot(res)
summary(res)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:car))
try(detach(package:nnet))
try(detach(package:MASS))
try(detach(package:hexbin))
try(detach(package:grid))
try(detach(package:lattice))
```
