Ordinal regression
=========================

```{r echo=FALSE}
opts_knit$set(self.contained=FALSE)
opts_chunk$set(tidy=FALSE, message=FALSE, warning=FALSE, comment="")
```

TODO
-------------------------

 - link to regressionLogistic, regressionMultinom

Install required packages
-------------------------

[`MASS`](http://cran.r-project.org/package=MASS), [`ordinal`](http://cran.r-project.org/package=ordinal), [`rms`](http://cran.r-project.org/package=rms), [`VGAM`](http://cran.r-project.org/package=VGAM)

```{r}
wants <- c("MASS", "ordinal", "rms", "VGAM")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Ordinal regression (proportional odds model)
-------------------------
    
### Simulate data
    
```{r}
set.seed(1.234)
N      <- 100
X1     <- rnorm(N, 175, 7)
X2     <- rnorm(N,  30, 8)
Ycont  <- 0.5*X1 - 0.3*X2 + 10 + rnorm(N, 0, 6)
Yord   <- cut(Ycont, breaks=quantile(Ycont), include.lowest=TRUE,
              labels=c("--", "-", "+", "++"), ordered=TRUE)
dfRegr <- data.frame(X1, X2, Yord)
```

### Using `lrm()` from package `rms`

logit(\(p(Y \geq g)\))

```{r}
library(rms)
(lrmFit <- lrm(Yord ~ X1 + X2, data=dfRegr))
```

### Using `vglm()` from package `VGAM`

logit(\(p(Y \geq g)\))

```{r}
library(VGAM)
vglmFit <- vglm(Yord ~ X1 + X2, family=propodds, data=dfRegr)
summary(vglmFit)
```

Equivalent:

```{r eval=FALSE}
summary(vglm(Yord ~ X1 + X2, family=cumulative(parallel=TRUE), data=dfRegr))
# not run
```

Cumulative logits without assumption of proportionality:

```{r eval=FALSE}
summary(vglm(Yord ~ X1 + X2, family=cumulative(parallel=FALSE), data=dfRegr))
# not run
```

### Using `clm()` from package `ordinal`

logit(\(p(Y \leq g)\))

```{r}
library(ordinal)
clmFit <- clm(Yord ~ X1 + X2, link="logit", data=dfRegr)
summary(clmFit)
```

### Using `polr()` from package `MASS`

logit(\(p(Y \leq g)\))

```{r}
library(MASS)
polrFit <- polr(Yord ~ X1 + X2, method="logistic", data=dfRegr)
summary(polrFit)
```

Predicted category membership
-------------------------

### Predicted category probabilities

```{r}
PhatCateg <- predict(lrmFit, type="fitted.ind")
head(PhatCateg)
```

```{r eval=FALSE}
predict(vglmFit, type="response")
predict(clmFit, subset(dfRegr, select=c("X1", "X2"), type="prob"))$fit
predict(polrFit, type="probs")
# not shown
```

### Predicted categories

```{r}
predict(clmFit, type="class")
```

```{r results='hide'}
(predCls <- predict(polrFit, type="class"))
# not shown
```

```{r}
categHat <- levels(dfRegr$Yord)[max.col(PhatCateg)]
all.equal(factor(categHat), predCls, check.attributes=FALSE)
```

Apply regression model to new data
-------------------------

### Simulate new data

```{r}
Nnew  <- 4
dfNew <- data.frame(X1=rnorm(Nnew, 175, 7),
                    X2=rnorm(Nnew,  30, 8),
                    Ycateg=ordered(sample(c("--", "-", "+", "++"), Nnew, TRUE),
                                   levels=c("--", "-", "+", "++")))
```

### Predicted class probabilities

```{r}
predict(lrmFit, dfNew, type="fitted.ind")
```

```{r eval=FALSE}
predict(vglmFit, dfNew, type="response")
predict(polrFit, dfNew, type="probs")
predict(clmFit, subset(dfNew, select=c("X1", "X2"), type="prob"))$fit
# not shown
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:ordinal))
try(detach(package:ucminf))
try(detach(package:Matrix))
try(detach(package:lattice))
try(detach(package:MASS))
try(detach(package:rms))
try(detach(package:Hmisc))
try(detach(package:survival))
try(detach(package:VGAM))
try(detach(package:splines))
try(detach(package:stats4))
```
