Multinomial regression
=========================

```{r echo=FALSE}
opts_knit$set(self.contained=FALSE)
opts_chunk$set(tidy=FALSE, message=FALSE, warning=FALSE, comment="")
```

TODO
-------------------------

 - link to regressionLogistic, regressionOrdinal

Install required packages
-------------------------

[`lmtest`](http://cran.r-project.org/package=lmtest), [`mlogit`](http://cran.r-project.org/package=mlogit), [`nnet`](http://cran.r-project.org/package=nnet), [`VGAM`](http://cran.r-project.org/package=VGAM)

```{r}
wants <- c("lmtest", "mlogit", "nnet", "VGAM")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Multinomial regression
----------------------

### Simulate data
    
```{r}
set.seed(1.234)
N      <- 100
X1     <- rnorm(N, 175, 7)
X2     <- rnorm(N,  30, 8)
Ycont  <- 0.5*X1 - 0.3*X2 + 10 + rnorm(N, 0, 6)
Ycateg <- cut(Ycont, breaks=quantile(Ycont), include.lowest=TRUE,
              labels=c("--", "-", "+", "++"))
dfRegr <- data.frame(X1, X2, Ycateg)
```

### Using `multinom()` from package `nnet`

Estimator based on neural networks -> slightly different results than `vglm()`, `mlogit()` below

```{r}
library(nnet)
mnFit <- multinom(Ycateg ~ X1 + X2, data=dfRegr)
summary(mnFit)
```

```{r}
library(lmtest)
lrtest(mnFit)
```

### Using `vglm()` from package `VGAM`

Estimator based on likelihood-inference

```{r}
library(VGAM)
vglmFitMN <- vglm(Ycateg ~ X1 + X2, family=multinomial(refLevel=1), data=dfRegr)
summary(vglmFitMN)
```

### Using `mlogit()` from package `mlogit`

Uses person-choice (long) format

```{r}
library(mlogit)
dfRegrL   <- mlogit.data(dfRegr, choice="Ycateg", shape="wide", varying=NULL)
mlogitFit <- mlogit(Ycateg ~ 0 | X1 + X2, reflevel="--", data=dfRegrL)
summary(mlogitFit)
```

```{r}
library(lmtest)
coeftest(mlogitFit)
```

Predicted category membership
-------------------------

### Predicted category probabilities

```{r}
PhatCateg <- predict(mnFit, type="probs")
head(PhatCateg)
```

```{r eval=FALSE}
predict(vglmFitMN, type="response")
fitted(mlogitFit, outcome=FALSE)
# not run
```

### Predicted categories

```{r}
(predCls <- predict(mnFit, type="class"))
```

```{r}
categHat <- levels(dfRegr$Ycateg)[max.col(PhatCateg)]
all.equal(factor(categHat), predCls, check.attributes=FALSE)
```

Apply regression model to new data
-------------------------

### Simulate new data

`predict.mlogit()` requires a new data frame in long format. Therefore also add new (irrelevant) categorical responses to enable reshaping the data frame with `mlogit.data()`.

```{r}
Nnew  <- 4
dfNew <- data.frame(X1=rnorm(Nnew, 175, 7),
                    X2=rnorm(Nnew,  30, 8),
                    Ycateg=factor(sample(c("--", "-", "+", "++"), Nnew, TRUE),
                                  levels=c("--", "-", "+", "++")))
dfNewL <- mlogit.data(dfNew, choice="Ycateg", shape="wide", varying=NULL)
```

### Predicted class probabilities

```{r}
predict(mnFit, dfNew, type="probs")
```

```{r eval=FALSE}
predict(vglmFitMN, dfNew, type="response")
predict(mlogitFit, dfNewL)
# not shown
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:mlogit))
try(detach(package:MASS))
try(detach(package:Formula))
try(detach(package:statmod))
try(detach(package:lmtest))
try(detach(package:zoo))
try(detach(package:maxLik))
try(detach(package:miscTools))
try(detach(package:nnet))
try(detach(package:VGAM))
try(detach(package:splines))
try(detach(package:stats4))
```
